# Every Open API file needs this
swagger: "2.0"
# Document metadata
info:
  version: "2023-10-10"
  title: Dayctionary-games
  description: Api de los juegos.
# URL data
host: localhost:8888
schemes:
  - http
consumes:
  - application/x-www-form-urlencoded
produces:
  - application/json

paths:
  /games:
    #http://localhost:8888/games/20231010
    get:
      responses:
        200:
          description: Successful response
          schema:
            $ref: "#/definitions/game"
        404:
          description: Not found. Juego no encontrado.
      description: Recibe el juego de hoy.
  /games/{date}:
    #http://localhost:8888/games/20231010
    get:
      parameters:
          - name: date
            in: path
            required: true
            type: string
            description: Fecha del juego con formato YYYYMMDD.
      responses:
        200:
          description: Successful response
          schema:
            $ref: "#/definitions/game"
        400:
          description: Bad request. La fecha no tiene el formato indicado.
        404:
          description: Not found. Juego no encontrado.
      description: Recibe el juego del día indicado.
  /games/create:
    #http://localhost:8888/games/create
    get:
      responses:
        200:
          description: Successful response
          schema:
            $ref: "#/definitions/game"
        428:
          description: Too many requests. Demasiadas peticiones.
      description: Genera un juego.
  /games/create/{word}:
    #http://localhost:8888/games/create/word
    get:
      parameters:
          - name: word
            in: path
            required: true
            type: string
            description: Palabra de la que se busca crear un juego.
      responses:
        200:
          description: Successful response
          schema:
            $ref: "#/definitions/game"
        404:
          description: Not found. Juego no encontrado, no hay información suficiente para crearlo.
        428:
          description: Too many requests. Demasiadas peticiones.
      description: Genera un juego a partir de una palabra.
definitions:
  phonetic:
    properties:
      audio:
        type: string
        description: Audio de la palabras.
      syllables:
        type: integer
        description: Número de sílabas de la palabras.
        minimum: 1
  phoneticSingle:
    properties:
      word:
        type: string
        description: Palabra a la que pertenece la fonética.
      phonetic:
        $ref: "#/definitions/phonetic"
  phonetics:
    type: array
    items:
      $ref: "#/definitions/phoneticSingle"
  definition:
    properties:
      text:
        type: string
        description: Definición de la palabra.
      type:
        type: string
        description: Tipo de palabra.
  definitionSingle:
    properties:
      word:
        type: string
        description: Palabra a la que pertenece la definición.
      definition:
        $ref: "#/definitions/definition"
  definitions:
    type: array
    items:
      $ref: "#/definitions/definitionSingle"
  game:
    properties:
      id:
        type: string
        description: Identificador único del juego.
      word:
        type: string
        description: Palabra del juego.
      date:
        type: string
        description: fecha con formato YYYYMMDD.
      synonym:
        type: string
      similarSynonyms:
        type: array
        items:
          type: string
      phonetic:
        $ref: "#/definitions/phonetic"
      similarPhonetics:
        $ref: "#/definitions/phonetics"
      definition:
        $ref: "#/definitions/definition"
      similarDefinitions:
        $ref: "#/definitions/definitions"

      
