# Every Open API file needs this
swagger: "2.0"
# Document metadata
info:
  version: "2023-10-10"
  title: Dayctionary-answers
  description: Api de las respuestas.
# URL data
host: localhost:8888
basePath: /answers
schemes:
  - http
consumes:
  - application/x-www-form-urlencoded
produces:
  - application/json

paths:
  /answer:
    #http://localhost:8888/answers/answer
    post:
      parameters:
          - name: answer
            in: body 
            schema:
              $ref: '#/definitions/gameAnswerDTO'
      responses:
        200:
          description: Successful response
          schema:
            $ref: "#/definitions/answerDTO"
        400:
          description: Bad request. Minijuego ya contestado.
        404:
          description: Not found. Usuario/Juego no encontrado.
      description: Recibe la palabra y el id del juego de hoy.
  /answer/{userId}/{gameId}:
    #http://localhost:8888/answers/answer/u53RiD/G4m3iD
    get:
      parameters:
          - name: userId
            in: path
            required: true
            type: string
            description: Identificador único de usuario.
          - name: gameId
            in: path
            required: true
            type: string
            description: Identificador único de juego.
      responses:
        200:
          description: Successful response
          schema:
            $ref: "#/definitions/answerDTO"
        404:
          description: Not found. Usuario/Juego/Respuesta no encontrada.
      description: Recibe la palabra y el id del juego del día indicado.
definitions:
  gameAnswerDTO:
    properties:
      userId:
        type: string
        description: Identificador único de usuario.
      gameId:
        type: string
        description: Identificador único de juego.
      minigame:
        type: string
        description: nombre de minijuego.
      word:
        type: string
        description: respuesta de minijuego.
  gameAnswer:
    properties:
      minigame:
        type: string
        description: nombre de minijuego.
      word:
        type: string
        description: respuesta de minijuego.
  gameAnswers:
    type: array
    items:
      $ref: "#/definitions/gameAnswer"
  answerDTO:
    properties:
      gameAnswers:
        $ref: "#/definitions/gameAnswers"
  
